### PR TITLE
 Expressions don't expand in single quotes, use double quotes for that.

### PR DESCRIPTION
**Pull request by mrmajik45**
Smol changes :P

**Status**: ?

**Reference**: https://github.com/mrmajik45/DietPi

**Commit list/description**:

- Replaced`'` with `"`

### CODE REVIEW

**Comment by mrmajik45** [comment]
@Fourdee @MichaIng

**Comment by MichaIng** [comment]
@mrmajik45
Note that in these cases it is wanted, that the regular expressions are not expended. We want the asterisk to be present in destination for. There are many other cases where we use single quotes, e.g. when we want to have a variable not expended in the main script, but inside the file we create or edit. 

Please ignore this remarks from code checkers accordingly. Mistakes of these kind would not survive our testing before releasing the code.

**Comment by MichaIng** [comment]
I will mark this PR as closed for above reason.

**Comment by mrmajik45** [comment]
I couldn't remember :(

**Comment by MichaIng** [comment]
No worries, it's good to have some recheck about this. In some cases code checker remarks have a point, in some cases a different coding is wanted or needed :wink:.

**Comment by mrmajik45** [comment]
@MichaIng Gotta delete and fork this again, lol. MOAR SPELLING!

**Comment by MichaIng** [comment]
@mrmajik45 
Okay, hope it works as you expect. Issue can be closed then?

**Comment by mrmajik45** [comment]
Yeah (Fall break now woo!)

**Pull request closed without merging**
